### ISSUE TITLE
this is not currently working for me on heroku

### ISSUE THREAD

**Issue by campgurus** [jayzes/heroku-buildpack-jpegoptim#2]
I am attempting to follow these instructions: https://github.com/jayzes/heroku-buildpack-optipng

However when I check the tools are not installed:

$ heroku run "optipng -v" -a blackops-staging *[master] 
Running optipng -v attached to terminal... up, run.1383
bash: optipng: command not found

$ heroku run "jpegoptim -v" -a blackops-staging *[master] 
Running jpegoptim -v attached to terminal... up, run.2893
bash: jpegoptim: command not found
If I attempt to reprocess images, I get a similar message:

$ heroku run rails c -a blackops-staging [master] 
Running rails c attached to terminal... up, run.6860
Loading staging environment (Rails 4.2.1)
irb(main):001:0> Article.find_each{|article| article.avatar.recreate_versions!}
Article Load (25.4ms) SELECT "articles". FROM "articles" ORDER BY "articles"."id" ASC LIMIT 1000
Attempting to optimize a jpeg without jpegoptim installed. Skipping...

Full code is here: https://github.com/BOWiki/BOW

Thanks!

**Comment by campgurus** [comment]
working now. never mind!

**Comment by jayzes** [comment]
@campgurus cool!
