### ISSUE TITLE
jpegoptim: command not found

### ISSUE THREAD

**Issue by pwz2k** [jayzes/heroku-buildpack-jpegoptim#3]
I am trying to get this working on Heroku, however in terminal I am getting the error:

```
jpegoptim: command not found
```

I have it installed via brew:

```
jpegoptim-1.4.2 already installed
```

I followed your steps and added .buildpacks to the root folder with contents:

```
https://github.com/jayzes/heroku-buildpack-jpegoptim
https://github.com/heroku/heroku-buildpack-ruby
```

Heroku is up to date with the latest code.

Here's the terminal:

```
$ heroku config:add BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi
Setting config vars and restarting areyoutaken... done, v96
BUILDPACK_URL: https://github.com/ddollar/heroku-buildpack-multi
$ git push heroku master
Everything up-to-date
$ heroku run "jpegoptim -V"
Running `jpegoptim -V` attached to terminal... up, run.2026
bash: jpegoptim: command not found
```

**Comment by jayzes** [comment]
You'll need to actually trigger a rebuild of the app in order for the buildpack to run and place the binary - your push didn't force a rebuild, it looks like there were no new commits to push.

Try something like this:

```
$ git commit --allow-empty -m "Empty commit to force a Heroku build"
$ git push heroku master
$ heroku run "jpegoptim -V"
```

**Comment by pwz2k** [comment]
Thanks, that worked!
